from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name="accueil"),
    path('inscription', register_view, name="inscription"),
    path('connexion', login_view, name="connexion"),
    path('deconnexion', logout, name="deconnexion"),
    path('profil', profil , name="profil"),
    path('profil_utilisateur/<str:id>', profil_utilisateur, name="profil_utilisateur"),
    path('add_plainte', add_plainte, name="add_plainte"),
    path('mes_plaintes', mes_plaintes, name="mes_plaintes"),
    path('mes_plaintes/<str:id>/view', view_plainte, name="view_plainte"),
    path('mes_plaintes/<str:id>/delete', delete_plainte, name="delete_plainte"),
    path('comments/<str:id>/delete', delete_comment, name="delete_comment"),
    path('comments/<str:id>/delete2', delete_comment2, name="delete_comment2"),
    path('comments/<str:id>/delete3/<str:from_id>', delete_comment3, name="delete_comment3"),
    path('comments/<str:id>/delete4/<str:from_id>', delete_comment4, name="delete_comment4"),
    path('chats', chats_sans_conversation, name="chats"),
    path('chats/<str:correspondant_id>', chats_avec_conversation, name="chat_user"),
    path('message/<str:id>/delete', delete_message, name="delete_message"),
    path('users', utilisateurs, name="users"),
    path('users/citoyens', utilisateurs_citoyen, name="users_citoyens"),
    path('users/autorites', utilisateurs_autorite, name="users_autorites"),
    path('users/techniciens', utilisateurs_technicien, name="users_techniciens"),
    path('users/admin', utilisateurs_admin, name="users_admin"),
    path('users/sys', utilisateurs_sys, name="users_sys"),
    path('users/add', add_user, name="add_user"),
    path('users/<str:id>/alter', alter_user, name="alter_user"),
    path('users/<str:id>/delete', delete_user, name="delete_user"),
    path('plaintes/autorite', plaintes_autorite, name="plaintes_autorite"),
    path('autorite_take/<str:plainte_id>', autorite_take, name="autorite_take"),
    path('plaintes/autorite/<str:plainte_id>/assign', assign_technicien, name="assign_technicien"),
    path('plaintes/technicien', plaintes_technicien, name="plaintes_technicien"),
    path('plaintes/technicien/<str:plainte_id>/on_intervention', turn_into_intervention, name="turn_into_intervention"),
    path('plaintes/technicien/<str:plainte_id>/on_intervention_end', turn_into_intervention_end, name="turn_into_intervention_end"),
    path('plaintes/autorite/<str:plainte_id>/resolve_ok', resolve_ok, name="resolve_ok"),
    path('plaintes/autorite/<str:plainte_id>/resolve_not_ok', resolve_not_ok, name="resolve_not_ok"),
    path('plaintes/autorite/<str:plainte_id>/reject_plainte', reject_plainte, name="reject_plainte"),
]